/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Loader: typeof import('./src/components/Loader.vue')['default']
  }
}
