name: Run changeset

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['.changeset/**.md']

permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-changeset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
          registry-url: https://registry.npmjs.org
      - uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version-file: .bun-version
      - run: bun install --frozen-lockfile
      - run: bun run check
      - run: bun run test:coverage
      - run: bunx playwright install --with-deps chromium firefox webkit
      - run: bun run test:browser
      - name: Version or publish packages
        uses: changesets/action@v2.1.2
        with:
          version-script: bun run version-packages
          publish-script: bun run release
          commit-message: 'chore(packages): version packages'
          pr-title: 'chore(packages): version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
