name: Test pull request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches:
      - "master"

jobs:
  validate:
    name: Test pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install packages dependencies only
        run: pnpm run ci:packages:install-deps

      - name: Build packages
        run: pnpm run ci:packages:build

      - name: Lint packages
        run: pnpm run ci:packages:lint

      - name: Check packages types
        run: pnpm run ci:packages:typecheck

      - name: Test packages
        run: pnpm run ci:packages:test